sudo: false
language: python
python:
  - "2.7"
  - "3.6"
  - "pypy"
  - "pypy3"
install:
  pip install .
script:
  - pprofile --threads 0 demo/threads.py
  - pprofile --format callgrind demo/threads.py
  - pprofile --statistic .01 demo/threads.py
  - demo/embedded.py
  - pprofile demo/threads.py
  - pprofile demo/empty.py
  - pprofile --format callgrind demo/empty.py
  - pprofile --statistic .01 demo/empty.py
  - pprofile --format callgrind --zipfile source_code.zip demo/threads.py
  - pprofile --format callgrind --zipfile source_code.zip demo/empty.py
  - pprofile --exclude-syspath demo/threads.py
  - pprofile --exclude-syspath --statistic .01 demo/threads.py
  - pprofile --include demo demo/encoding.py
  - LC_CTYPE=ISO-8859-15 pprofile --include demo demo/encoding.py
  - pprofile demo/empty.py -search
  - pprofile -- demo/empty.py -search
  - pprofile demo/recurse.py
  - pprofile demo/recurse2.py
  - pprofile demo/recurse3.py
  - pprofile demo/recurse4.py
  - pprofile demo/twocalls.py
  - pprofile demo/twocalls2.py
